{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "ads.fullname" . }}-audit
  labels:
    {{- include "ads.labels" . | nindent 4 }}
spec:
  hostnames:
    - {{ .Values.audit.httpRoute.hostname | quote }}
  parentRefs:
    - name: {{ .Values.httpRoute.gateway.name }}
      namespace: {{ .Values.httpRoute.gateway.namespace }}
      sectionName: {{ .Values.httpRoute.gateway.sectionName }}
  rules:
    - filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Port
                value: "443"
      backendRefs:
        - name: {{ include "ads.fullname" . }}-audit
          port: {{ .Values.audit.service.port }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "ads.fullname" . }}-audit
  labels:
    {{- include "ads.labels" . | nindent 4 }}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: {{ include "ads.fullname" . }}-audit
      sectionName: https
  validation:
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: {{ .Values.httpRoute.backendTLS.caConfigMapName }}
    hostname: {{ .Values.audit.httpRoute.hostname | quote }}
{{- end }}
