apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "ads.fullname" . }}-audit
  labels:
    {{- include "ads.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.audit.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "ads.auditSelectorLabels" . | nindent 4 }}
---
{{- if .Values.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "ads.fullname" . }}-audit
  labels:
    {{- include "ads.labels" . | nindent 4 }}
spec:
  secretName: {{ include "ads.auditSecretName" . }}
  issuerRef:
    name: {{ .Values.tls.certManager.issuer.name }}
    kind: {{ .Values.tls.certManager.issuer.kind }}
    group: {{ .Values.tls.certManager.issuer.group }}
  dnsNames:
    - {{ printf "%s-audit" (include "ads.fullname" .) | quote }}
    - {{ printf "%s-audit.%s" (include "ads.fullname" .) .Values.namespace | quote }}
    - {{ printf "%s-audit.%s.svc" (include "ads.fullname" .) .Values.namespace | quote }}
    - {{ printf "%s-audit.%s.svc.cluster.local" (include "ads.fullname" .) .Values.namespace | quote }}
{{- end }}
