apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "ads.fullname" . }}
  labels:
    {{- include "ads.labels" . | nindent 4 }}
data:
  ADS_KEYCLOAK_WELL_KNOWN_URL: {{ .Values.keycloak.wellKnownUrl | quote }}
  ADS_KEYCLOAK_ISSUER: {{ .Values.keycloak.issuer | quote }}
  ADS_KEYCLOAK_CLIENT_ID: {{ .Values.keycloak.clientId | quote }}
  ADS_KEYCLOAK_AUDIENCE: {{ .Values.keycloak.audience | quote }}
  ADS_KEYCLOAK_ROLE: {{ .Values.keycloak.role | quote }}
  ADS_KEYCLOAK_AUDITOR_ROLE: {{ .Values.keycloak.auditorRole | quote }}
  ADS_AUDITOR_ALLOWED_AZP: {{ .Values.audit.keycloak.clientId | quote }}
  ADS_PUBLIC_BASE_URL: {{ include "ads.publicBaseUrl" . | quote }}
  ADS_BIND_HOST: "0.0.0.0"
  ADS_PORT: {{ .Values.service.port | quote }}
  ADS_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  ADS_ENGINE_REQUEST_TOPIC: {{ .Values.kafka.requestTopic | quote }}
  ADS_ENGINE_OUTPUT_TOPIC: {{ .Values.kafka.outputTopic | quote }}
  ADS_ENGINE_CONSUMER_GROUP: {{ .Values.kafka.consumerGroup | quote }}
  ADS_PREFERENCES_BASE_URL: {{ include "ads.preferencesBaseUrl" . | quote }}
  ADS_PREFERENCES_AUDIENCE: {{ .Values.preferences.audience | quote }}
  ADS_ENGINE_AUDIENCE: {{ .Values.engine.keycloak.audience | quote }}
  ADS_ENGINE_ALLOWED_AZP: {{ .Values.engine.keycloak.allowedAzp | quote }}
  ADS_TLS_CERT_PATH: "/certs/tls.crt"
  ADS_TLS_KEY_PATH: "/certs/tls.key"
  ADS_POLICY_URL: {{ include "ads.policyUrl" . | quote }}
  {{- with include "ads.caBundlePath" . }}
  ADS_TLS_CA_BUNDLE: {{ . | quote }}
  {{- end }}
  {{- include "ads.unlistedModels" . }}
