apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "ads.fullname" . }}-context-compactor
  labels:
    {{- include "ads.labels" . | nindent 4 }}
    app.kubernetes.io/component: ads-context-compactor
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.contextCompactor.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "ads.contextCompactorSelectorLabels" . | nindent 4 }}
