apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ads.fullname" . }}-egress-controlplane
  labels:
    {{- include "ads.labels" . | nindent 4 }}
    app.kubernetes.io/component: ads-egress-controlplane
spec:
  replicas: {{ .Values.egressControlplane.replicaCount }}
  selector:
    matchLabels:
      {{- include "ads.egressSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ads.egressSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ads.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ads-egress-controlplane
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.egressControlplane.image.repository }}:{{ .Values.egressControlplane.image.tag }}"
          imagePullPolicy: {{ .Values.egressControlplane.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- include "ads.applicationNodeSelector" . | nindent 8 }}
        {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
