apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ads.fullname" . }}-engine
  labels:
    {{- include "ads.labels" . | nindent 4 }}
    app.kubernetes.io/component: ads-engine
spec:
  replicas: {{ .Values.engine.replicaCount }}
  selector:
    matchLabels:
      {{- include "ads.engineSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ads.engineSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ads.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ads-engine
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.engine.image.repository }}:{{ .Values.engine.image.tag }}"
          imagePullPolicy: {{ .Values.engine.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "ads.fullname" . }}-engine
          {{- if .Values.tls.caBundle.secretName }}
          volumeMounts:
            - name: ca
              mountPath: /ca
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.tls.caBundle.secretName }}
      volumes:
        - name: ca
          secret:
            secretName: {{ .Values.tls.caBundle.secretName }}
            items:
              - key: {{ .Values.tls.caBundle.key | default "ca.crt" }}
                path: ca.crt
      {{- end }}
      nodeSelector:
        {{- include "ads.applicationNodeSelector" . | nindent 8 }}
        {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
