apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "ads.fullname" . }}-engine
  labels:
    {{- include "ads.labels" . | nindent 4 }}
    app.kubernetes.io/component: ads-engine
type: Opaque
stringData:
  ADS_ENGINE_KEYCLOAK_CLIENT_SECRET: {{ .Values.secrets.engineKeycloakClientSecret | quote }}
  ADS_ENGINE_DATABASE_URL: {{ .Values.engine.database.url | quote }}
