{{- if .Values.guardrail.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ads.fullname" . }}-guardrail
  labels:
    {{- include "ads.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.guardrail.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "ads.guardrailSelectorLabels" . | nindent 4 }}
---
{{- if .Values.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ads.fullname" . }}-guardrail
  labels:
    {{- include "ads.labels" . | nindent 4 }}
spec:
  secretName: {{ include "ads.guardrailSecretName" . }}
  issuerRef:
    name: {{ .Values.tls.certManager.issuer.name }}
    kind: {{ .Values.tls.certManager.issuer.kind }}
    group: {{ .Values.tls.certManager.issuer.group }}
  dnsNames:
    - {{ printf "%s-guardrail" (include "ads.fullname" .) | quote }}
    - {{ printf "%s-guardrail.%s" (include "ads.fullname" .) .Release.Namespace | quote }}
    - {{ printf "%s-guardrail.%s.svc" (include "ads.fullname" .) .Release.Namespace | quote }}
    - {{ printf "%s-guardrail.%s.svc.cluster.local" (include "ads.fullname" .) .Release.Namespace | quote }}
{{- end }}
{{- end }}
