apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ads.fullname" . }}-preferences
  labels:
    {{- include "ads.labels" . | nindent 4 }}
    app.kubernetes.io/component: ads-preferences
type: Opaque
stringData:
  ADS_PREFERENCES_DATABASE_URL: {{ required "preferences.database.url is required" .Values.preferences.database.url | quote }}
