{{- if and .Values.persistence.enabled .Values.persistence.pv.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ default (printf "%s-pv" (include "ads.fullname" .)) .Values.persistence.pv.name }}
  labels:
    {{- include "ads.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: {{ .Values.persistence.pv.hostPath | quote }}
    type: DirectoryOrCreate
{{- end }}
