{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ads.fullname" . }}
  labels:
    {{- include "ads.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.pv.enabled }}
  volumeName: {{ default (printf "%s-pv" (include "ads.fullname" .)) .Values.persistence.pv.name }}
  storageClassName: ""
  {{- else if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
