apiVersion: v1
kind: Service
metadata:
  name: {{ include "ads.sandboxName" (dict "root" . "component" "manager") }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ads.labels" . | nindent 4 }}
    app.kubernetes.io/component: ads-sandbox-manager
spec:
  type: ClusterIP
  ports:
    - name: https
      port: {{ .Values.sandbox.manager.port }}
      targetPort: https
  selector:
    {{- include "ads.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ads-sandbox-manager
