apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "ads.fullname" . }}
  labels:
    {{- include "ads.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADS_KEYCLOAK_CLIENT_SECRET: {{ .Values.secrets.keycloakClientSecret | quote }}
  ADS_SESSION_SECRET: {{ .Values.secrets.sessionSecret | quote }}
